### ISSUE TITLE
About the training details

### ISSUE THREAD

**Issue by OrangeSodahub** [Runsong123/PCF-Lift#1]
This is an excellent work.

I have some questions after checking the paper. Did you use the 3D annoatations to supervise the feature learning? Thanks!

**Comment by Runsong123** [comment]
Thanks for your interest.

No, we only use the network-inferred 2D annotations to supervise the 3D feature learning.

Runsong

**Comment by OrangeSodahub** [comment]
Thanks! But I'm still confusing about what exactly are "network-inferred 2D annotations", could you explain more about that?

**Comment by Runsong123** [comment]
Sure. The term "network-inferred 2D annotation" refers to the segmentation predictions from a 2D model, such as M2F, SAM, etc.

**Comment by OrangeSodahub** [comment]
Thanks I got it. And Q2: in your paper, the "Probabilistic Contrastive Loss" namely L_pixel_contra and L_concen also need the positive and negative pixel pairs, so how did you get those pairs? Like the "Cross-view Constraint"?

**Comment by Runsong123** [comment]
For L_pixel_contra and L_concen, the positive and negative pixel pairs are defined in an individual view according to corresponding instance segmentation. Specifically, a positive pair consists of two pixels with the same instance ID, and conversely, a negative pair consists of pixels with different instance IDs. Note that, we explained these in paper Sec 3.2 (Probabilistic Contrastive Loss).

**Comment by OrangeSodahub** [comment]
Thanks for your explaination. Yes I see that. But the further question is, those instance IDs are generated by 2D Foundatioin Model you mentioned above? Thus these positive and negative pairs need to be located in single view, right? you also claimed for negative pairs in Sec. 3.2

**Comment by OrangeSodahub** [comment]
Thanks all my questions are addressed

**Comment by Runsong123** [comment]
> Thanks for your explaination. Yes I see that. But the further question is, those instance IDs are generated by 2D Foundatioin Model you mentioned above? Thus these positive and negative pairs need to be located in single view, right? you also claimed for negative pairs in Sec. 3.2

Yes, the probabilistic contrastive loss (L_pixel_contra and L_concen) is defined only within a single view.
