### ISSUE TITLE
How to train?

### ISSUE THREAD

**Issue by ShunkaiZhou** [Runsong123/PCF-Lift#3]
Dear author,

Thanks for your great work. I want to train Replica but I find three train.py (train_panopli_tensorf.py, train_panopli_tensorf_learned_covariance_v2_smaller_clamp.py, train_panopli_tensorf_learned_covariance_v2_smaller_clamp_cross_constraint.py) in your project. 

What's the difference among them and which one I should use?

Thank you so much and best wishes

**Comment by Runsong123** [comment]
Hello, you may want to take a look at the "train.sh" script and follow the train.sh script to optimize for new scenes.

The train_panopli_tensorf.py script is used to initialize the Gaussian means, and then you can use the train_panopli_tensorf_learned_covariance_v2_smaller_clamp.py script to optimize the complete Gaussian features. Additionally, the train_panopli_tensorf_learned_covariance_v2_smaller_clamp_cross_constraint.py script is a version that includes an additional cross-view constraint.


Bests,
Runsong

**Comment by ShunkaiZhou** [comment]
OK! I will try it.
Thank you very much and best wishes
